import streamlit as st
import sys
sys.path.append('.')
from utils.db import run_query
from utils.ai import ask_openai

st.set_page_config(page_title="AI Insights", page_icon="🤖", layout="wide")
st.title("🤖 AI Insights — Ask the Data")
st.markdown("---")
st.markdown("Ask any business question about the Olist e-commerce dataset in plain English.")

# Build data context from real database
rev = run_query('SELECT ROUND(SUM(payment_value),2) as total FROM payments')
orders = run_query('SELECT COUNT(*) as total FROM orders')
avg_score = run_query('SELECT ROUND(AVG(review_score),2) as avg FROM reviews')
late_orders = run_query('''
    SELECT ROUND(100.0 * SUM(CASE WHEN julianday(order_delivered_customer_date)
    > julianday(order_estimated_delivery_date) THEN 1 ELSE 0 END)
    / COUNT(*), 2) as pct
    FROM orders
    WHERE order_delivered_customer_date IS NOT NULL
    AND order_estimated_delivery_date IS NOT NULL
''')
top_cats = run_query('''
    SELECT t.product_category_name_english, COUNT(*) as cnt
    FROM order_items i
    JOIN products p ON i.product_id = p.product_id
    JOIN translations t ON p.product_category_name = t.product_category_name
    GROUP BY t.product_category_name_english
    ORDER BY cnt DESC LIMIT 5
''')
avg_delivery = run_query('''
    SELECT ROUND(AVG(julianday(order_delivered_customer_date)
    - julianday(order_purchase_timestamp)), 1) as avg_days
    FROM orders
    WHERE order_delivered_customer_date IS NOT NULL
''')

context = f"""
Total revenue: R$ {rev['total'][0]:,}
Total orders: {orders['total'][0]:,}
Average review score: {avg_score['avg'][0]} out of 5
Percentage of late orders: {late_orders['pct'][0]}%
Average delivery time: {avg_delivery['avg_days'][0]} days
Top 5 product categories by volume: {', '.join(top_cats['product_category_name_english'].tolist())}
Dataset period: 2016 to 2018, Brazilian e-commerce marketplace
"""

st.markdown("### 💬 Ask a Question")
question = st.text_input(
    "Type your question here:",
    placeholder="e.g. What are the main reasons for customer dissatisfaction?"
)

if st.button("🤖 Ask OpenAI", use_container_width=True):
    if question:
        with st.spinner("OpenAI is thinking..."):
            answer = ask_openai(question, context)
        st.markdown("### 📊 Answer")
        st.write(answer)
        st.markdown("---")
        st.caption("Answer generated by Open AI based on Olist dataset statistics.")
    else:
        st.warning("Please type a question first!")

st.markdown("---")
st.markdown("### 💡 Example Questions to Try")
col1, col2 = st.columns(2)
with col1:
    st.markdown("""
    - What drives customer dissatisfaction?
    - Which product category is most popular?
    - How is the overall revenue performance?
    """)
with col2:
    st.markdown("""
    - What percentage of orders are late?
    - What is the average delivery time?
    - How satisfied are customers overall?
    """)